{
    'name': 'jmlm/odoo Development Tutorials',
    'version': '14.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'jmlm/Odoo Development Tutorials For Beginners',
    'sequence': '2',
    'license': 'AGPL-3',
    'author': 'Odoo Mates',
    'maintainer': 'Odoo Mates',
    'website': 'http://odoomates.tech',
    'live_test_url': 'https://www.youtube.com/watch?v=BDepk0LhVuI&list=PLqRRLx0cl0hoJhjFWkFYowveq2Zn55dhM&index=1',
    'depends': ['base', 'mail', 'sale', 'web', ],
    'demo': [],
    'data': [
        'security/ir.model.access.csv',
        'data/secquence.xml',
        'views/appointment.xml',
        'views/patient.xml',
        'reports/report.xml',
        'reports/patient_card.xml',
        #'reports/my_header.xml',
        #'reports/my_footer.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
# Video Explanation: https://www.youtube.com/watch?v=BDepk0LhVuI&list=PLqRRLx0cl0hoJhjFWkFYowveq2Zn55dhM&index=1
